### ISSUE TITLE
Update fails to run

### ISSUE THREAD

**Issue by oudeismetis** [thinknimble/tn-cli#18]
Ran into an issue where a command didn't exist. (ideally the error for that would tell me to try updating)
As a result I tried to run `tn update`, but that erred as well.

![image](https://github.com/user-attachments/assets/5021a4ae-a305-4d96-8be8-786813e65a01)

**Comment by oudeismetis** [comment]
Quickly just tried to delete that repo and try again, but naturally got this error 😄 

![image](https://github.com/user-attachments/assets/f0ea387b-8617-4631-b4ed-342448c3dc25)

**Comment by whusterj** [comment]
I think `update` was broken in the first version I rolled it out.

So to fix:

```bash
cd ~/.tn/cli
git pull
```

Since you deleted it, then rerun install or:

```bash
git clone git@github.com:thinknimble/tn-cli.git ~/.tn/cli
```

**Comment by oudeismetis** [comment]
Says I have the latest code when manually pulling. Still getting a Justfile error for Bedrock
