### ISSUE TITLE
Move config for prs

### ISSUE THREAD

**Issue by paribaker** [thinknimble/tn-cli#20]
`tn gh-all-prs` relies on a config file to be present in the directory where the CLI is, so if you have it in root it looks for `.config` IMO this should be a config inside of a directory e.g `.tncli/.config` to avoid any clashes with any other files in the root.

**Comment by whusterj** [comment]
Ah, my bad! `.config` should definitely be global. I meant for it to live in `~/.tn/config`. That's how the AWS CLI does it. 

Separately, I'm thinking we need to come up with some way to write reliable tests that can catch issues like this.

**Comment by whusterj** [comment]
I'll handle this as part of #14
